version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dice40k-backend
    ports:
      - "8000:8000"
    restart: always
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dice40k-frontend
    ports:
      - "8088:80"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
