[package]
name = "dice40k"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
actix-web = "4.9.0"
serde = { version = "1.0", features = ["derive"] }
actix-cors = "0.7.0"
dotenvy = "0.15.7"
